# Generated by Django 5.1.3 on 2024-11-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bankloan',
            fields=[
                ('Name', models.CharField(max_length=30)),
                ('Account_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Loan_amount', models.IntegerField()),
                ('Interest_amount', models.FloatField()),
                ('DOB', models.DateField()),
            ],
        ),
    ]
